import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styled from 'styled-components'

const Container = styled.div`
scroll-snap-type: y mandatory;
overflow-y: scroll;
height: 100vh;
`
const Section = styled.section`
height: 100vh;
scroll-snap-align: start;
`
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='container'>
            <section className='one section'>
              <h1>first</h1>
            </section>
            <section className='two section'>
              <h1>two</h1>
            </section>
            <section className='three section'>
              <h1>three</h1>
            </section>
        </div>
      </main>
{/* 
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}